version: '3'
services:
#mssql docker
  etaxi-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: etaxi-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MojaSifra123!
    ports:
      - 1433:1433
    expose:
      - 1433
    
    

  etaxi-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:eTaxiConnectionStringDocker=Server=etaxi-sql, 1433;Database=eTaxi;User=sa;Password=MojaSifra123!;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 7152:7152
    
   
    
      
     