version: '3'
services:
#mssql docker
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672


  etaxi-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: etaxi-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MojaSifra123!
    ports:
      - 1433:1433
    expose:
      - 1433
  
  notification-service:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.notificationService
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VIRTUALHOST=/
    depends_on:
      - rabbitmq
    ports:
      - 7153:80
    

  etaxi-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:eTaxiConnectionStringDocker=Server=etaxi-sql, 1433;Database=eTaxi;User=sa;Password=MojaSifra123!;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VIRTUALHOST=/
    ports:
      - 7152:7152
    volumes:
      - .:/src
    
   
    
      
     